name: Translate book

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Execute script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: deno task translate

      - name: Format
        run: deno fmt book/*

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || (git commit -a -m "update" --allow-empty)
          git push origin main
